# Generated by Django 6.1.1 on 2026-10-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_author_book_category_delete_livro_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, to='biblioteca.category'),
        ),
    ]
