# Generated by Django 6.1.2 on 2026-10-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_author_category_remove_livro_autor_alter_livro_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name_plural': 'authors'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
