# Generated by Django 6.1.1 on 2026-10-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors_tmp',
            field=models.ManyToManyField(blank=True, related_name='books_tmp', to='biblioteca.author'),
        ),
    ]
