# Generated by Django 6.1.1 on 2026-10-10 21:04

from django.db import migrations


def copiar_autores(apps, schema_editor):
    Book = apps.get_model('biblioteca', 'Book')
    
    for book in Book.objects.all():
        if book.authors:
            book.authors_tmp.add(book.authors)
            book.save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_book_authors_tmp'),
    ]

    operations = [
        migrations.RunPython(copiar_autores),
    ]
