# Generated by Django 6.1.2 on 2026-10-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='categories',
            field=models.ManyToManyField(to='biblioteca.category'),
        ),
    ]
