# Generated by Django 6.1.2 on 2026-10-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_alter_livro_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='authors',
            field=models.ManyToManyField(related_name='bookss', to='biblioteca.author'),
        ),
    ]
