# Generated by Django 6.1.2 on 2026-10-09 19:04

from django.db import migrations


def copiar_relacionamentos(apps, schema_editor):
    Livro = apps.get_model('biblioteca', 'Livro')
    
    for livro in Livro.objects.all():
        livro.authors.add(livro.author)

class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_livro_authors'),
    ]

    operations = [
        migrations.RunPython(copiar_relacionamentos),
    ]