# Generated by Django 6.1.1 on 2026-10-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_remove_book_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authors_tmp',
            new_name='authors',
        ),
    ]
